### ISSUE TITLE
ProgramCall setParameterList dumps stack trace when system_ not set. 

### ISSUE THREAD

**Issue by jeber-ibm** [IBM/JTOpen#103]
Running the JDBC test bucket from the JTOpen-test project using

java test.RegressionTest -system $SYSTEM -uid $UID -pwd $PWD -pwrSys $PWRUID,$PWRPWD -tc ProgramCall

Exception information appears in the output. 

PgmConstructor  15   SUCCESSFUL time 0 ms ended at Fri Jul 07 10:22:13 CDT 2023
java.lang.NullPointerException
	at com.ibm.as400.access.ProgramCall.setParameterList(ProgramCall.java:870)
	at test.PgmConstructor.Var016(PgmConstructor.java:444)
...
PgmConstructor  16   SUCCESSFUL time 2 ms ended at Fri Jul 07 10:22:13 CDT 2023

Look like this code is dumping the stack trace. 

    public void setParameterList(ProgramParameter[] parameterList) throws PropertyVetoException
    {
        if (Trace.traceOn_) Trace.log(Trace.DIAGNOSTIC, this, "Setting parameter list."); //@L8
        if (parameterList == null) {
            throw new NullPointerException("parameterList");
        } 
        //@J3 - Start
        //boolean isV7R2 = false;//@RCD
       // boolean isV7R1 = false;//@N6A//@RCD
        boolean isSupport255 = false;//@RCA
        try {
          //isV7R2 = system_.getVRM() == 0x00070200; //@RCD
          //isV7R1 = system_.getVRM() == 0x00070100;//@RCD //@N6A V7R1 with ptf SI55519 supported parameter with max 255
          isSupport255 = (system_.getVRM() >= 0x00070100);//@RCA
        } catch(Exception e) {
          **e.printStackTrace();**
        }

The code should handle the case where the system is not yet defined and not print a stack trace to the stderr

**Comment by ThePrez** [comment]
Closing as completed by #106
