### ISSUE TITLE
Feature request: convertToNull for 0001-01-01

### ISSUE THREAD

**Issue by DSEyers** [IBM/JTOpen#107]
We have date fields with value 0001-01-01 instead of nulls and I am told some rpg developers back then had no choice as db2/rpg code did not support nulls.  It does now and one solution is to update to nulls, but we have quite a few programs so take a while to test/change the older application BEs/UIs.

As we now have Java programs using jdbc driver we would like to have the convertToNull jdbc property

We are using IBM i 7.4 and JTopen 11.2.

Originaly we were getting very slow performance/jdbc conversion but resolved by appending param to driver URL ";date format=iso" (big thanks to John Eberhard). Ref: https://sourceforge.net/p/jt400/bugs/479/

```
-> java -jar jt400.jar "jdbc:as400:$SYSTEM"";date format=iso" $USERID $PASSWORD 
>select date('0001-01-01') from sysibm.sysdummy1
```

I've tried adding convertToNull and looked at the source code but not there zeroDateTimeBehavior with value of CONVERT_TO_NULL or convertToNull.  But thats more MySql but could be added as looks like db2 dates start at 0001-01-01. https://www.db2tutorial.com/db2-basics/db2-date/

**Comment by jeber-ibm** [comment]
Seems like you need to adjust your JDBC program to account for this.  If you get a date value of 0001-01-01, then your program should convert to null.   I don't think this would be of broad enough usage to add a new JDBC property for this.
