### ISSUE TITLE
JDBC connection slow for Windows Server 2019 and 2022

### ISSUE THREAD

**Issue by JMarkMurphy** [IBM/JTOpen#108]
Trying to determine where to get help for this issue, but I am having performance issues with JDBC and IBM i when the requester is Windows 2019 or 2022. This is compared to running on Windows 2016 which is about 100x faster, literally.

I am using Talend Open Studio v8.0 with Java 17 and jtOpen v9.8 against IBM i v7.2.

This runs a test job in Talend at around 2000 rows per second when running under Windows 2016, but only gets to 17 rows per second when running under Windows 2022. I don't know whether the issue is Windows or jtOpen, but JDBC connections to MS SQL Server are fast in the same setting.

Problem is, there are no errors, just reduced performance. I see a similar performance reduction in Windows 2019 as well, but shifting between Java 8, and Java 11 does not change the performance significantly, and using Talend version 7.3 does not change the performance significantly either.

I don't believe it is a network issue as there is only a single hop between the Talend server and IBM i. They are on the same subnet.

What can I look at to diagnose this better? Or do you know of any change in Windows Server that would affect JDBC performance like this?

**Comment by jboarman** [comment]
I've run into similar issues, with some differences in how I'm seeing the issues (see #110).  I've tried the JDBC driver from both Windows and Linux, and both environments exhibit the same severe slowness issues.

**Comment by jeber-ibm** [comment]
You may be hitting a problem with Nagle's algorithm used by Windows (see https://sourceforge.net/p/jt400/bugs/454/). 

Can you try using the "tcp no delay=true" JDBC property to see if that fixes the problem?

**Comment by DanielNovo** [comment]
> You may be hitting a problem with Nagle's algorithm used by Windows (see https://sourceforge.net/p/jt400/bugs/454/).
> 
> Can you try using the "tcp no delay=true" JDBC property to see if that fixes the problem?

Hi @jeber-ibm, 

Can you confirm how tcp no delay property should be written on a jdbc url?

jdbc:as400://serverip;trace=false;naming=sql;date format=iso;prompt=false;tcpNoDelay=true;

or 

jdbc:as400://serverip;trace=false;naming=sql;date format=iso;prompt=false;setTcpNoDelay=true;

or

jdbc:as400://serverip;trace=false;naming=sql;date format=iso;prompt=false;tcp no delay=true;

I cannot find the propertie list to check this, is there a page with this information? 

Thanks a lot

**Comment by jeber-ibm** [comment]
It's "tcp no delay=true".  If you take a trace, you will see it being accepted. 

java -Dcom.ibm.as400.access.Trace.category=JDBC -jar jt400.jar "jdbc:as400:$SYSTEM;tcp no delay=true" $USERID $PASSWORD 
...
Tue Jan 23 13:09:20:182 CST 2024  as400@setString: Properties user=...;tcp no delay=true; (1398574412) : tcp no delay = "true".
..

The jdbc properties are in the javadoc at com/ibm/as400/access/doc-files/JDBCProperties.html.  A link exists in the AS400JDBCDriver javadoc.
