### ISSUE TITLE
JT400 vs IBM i Access ODBC Driver -- Major Performance Issues

### ISSUE THREAD

**Issue by jboarman** [IBM/JTOpen#110]
Why would an old ODBC driver be over 10x faster than a recent version of the JT400 driver?

We have an internal application that is accessing an AS/400 DB2 instance using the Windows 32-bit ODBC driver labeled "iSeries Access ODBC Driver (v13.64.14)".

However, on the same machine, we've run v11.2 of JTOpen JDBC driver using 2 different applications, and the same SQL queries take _**several hours** compared to only about **10 minutes**_ on the older ODBC driver.

As a side question ... how does one get paid support for this driver?  (Though I've meticulously compared the settings between these two use cases, I'm hoping there is a bonehead mistake that someone more knowledgeable in DB2 for iSeries might be able to point out!)

----
### UPDATE
**Issue:** The driver was throwing tons of warnings due to an unexpected date format exception found in the trace log.  The internal exceptions are extremely expensive and slow down the query by about 100x on a number of experiments as compared to the same query run via IBM's ODBC driver.

**Resolution:** Adding `date format=iso` to the JDBC url resolves this problem by matching the default format used by the ODBC driver (and what clients like DBeaver think is the default setting but apparently is not for the JDBC driver).  Ideally, the next breaking version of JTOpen might consider going with this standard as the default.

**Comment by JMarkMurphy** [comment]
One gets paid software support by paying the software support for thier IBM i license.

**Comment by kadler** [comment]
As @JMarkMurphy said, if you have active SWMA for the IBM i OS, you can open a support ticket for ODBC and/or JDBC drivers.

**Comment by jboarman** [comment]
Thanks @JMarkMurphy and @kadler ... It's taking a bit to navigate through IBM's support, but we're getting that journey started.

For reference, here is a visual example demonstrating the speed difference between the 2 drivers (ODBC vs JDBC).  For the same query, it's taking **~1 second via ODBC** and **~120 seconds via JDBC**!

Note that what we really need is a fast JDBC driver to use in a Databricks environment to load data from DB2 for reporting.  Though this is an example from Windows, it exhibits the exact same performance profile as when executed from a Linux environment:

![image](https://github.com/IBM/JTOpen/assets/1108065/b8e94265-a220-4693-9683-fa48c4621eec)

It seems strange that both this ticket and #108 are seeing slow relative performance on the order of a 100x speed difference.  Perhaps that is coincidental, but I am curious if there are any speed metrics that have been tracked to validate any expected performance levels?

**Comment by JMarkMurphy** [comment]
This is very strange. I am seeing this as well., though JDBC is only twice as slow as ODBC, even though it goes through the, now defunct, JDBC-ODBC bridge from Sun. I would expect that to be slower.

**Comment by jeber-ibm** [comment]
Here are a few tips that I can think of. 

1.  Make sure that the block size is set to the 512 maximum by adding ;block size=512 to the JDBC URL. 
2.  Make sure that the query you are running is not creating any warnings.  Creating a warning in JDBC is VERY expensive, as it creates a Java exception (which includes the stack trace).  If the query creates warning, the JDBC property "ignore warnings" can be used to specify the warnings to ignore. 
3. If the query returns lobs, you may need to adjust the JDBC property lob threshold ( so that lobs are returned in-line instead of as locators).

**Comment by jboarman** [comment]
Thanks @jeber-ibm for those suggestions.  After trying these, I am curious why the `ignore warnings` setting doesn't seem to be working!  (so far I'm not seeing any improvements and the setting appears to be ignored for some reason)

**The trace file shows the setting is being picked up**
`Thread[Connect to 'JDBC (JTOpen)',5,main]  as400: Properties  (919350410) : ignore warnings = "181,466,42703".`

**Though we are ignoring this warning, it is still being reported in the trace log**
```
Sat Aug 12 12:49:28:427 CDT 2023
as400: Connection S10D4072 (1214679991)
Posting warning, id: 1
error class: 1
return code: 181
reason:
  [SQL0181] Value in date, time, or timestamp string not valid.
  Cause:
    The string representation of a date, time or timestamp value is not in the acceptable range. *N is either the
    character string constant that is not valid or the column or host variable that contained the string. If the name
    is *N, then the value was found in an expression specified in the statement. If the value was found in a host
    variable, then the host variable number is 0.

  The proper ranges for date, time, or timestamp values are as follows:
    -- The range for years is from 0001 to 9999. For date formats *MDY, *YMD, *DMY, and *JUL, the year must be in the
       range 1940 to 2039.
    -- The range for months is from 1 to 12.
    -- The range for days is from 1 - 30 for April, June, September, and November, from 1 - 28 for February and from 1
       to 31 for all other months. In a leap year, the range for February can be from 1 to 29.
    -- The range for days in a Julian date is from 001 to 366 for a leap year or 001 to 365 days for all other years.
    -- The range for hours is from 0 to 24. If the hour is 24, then the other parts of the time values must be zeros.
       If the time format is USA, then the hour cannot be greater than 12.
    -- The range for minutes is from 0 to 59.
    -- The range for seconds is from 0 to 59.
    -- The range for fractional seconds is from 0 to 999999999999.

  Recovery:
    Ensure that the date, time, or timestamp value conforms to the ranges for the data type it represents. Try the
    request again.

state: 01534.java.sql.SQLWarning:

	at com.ibm.as400.access.JDError.getSQLWarning(JDError.java:347)
	at com.ibm.as400.access.JDServerRowCache.fetch(JDServerRowCache.java:363)
	at com.ibm.as400.access.JDServerRowCache.fetch(JDServerRowCache.java:270)
	at com.ibm.as400.access.JDServerRowCache.next(JDServerRowCache.java:804)
	at com.ibm.as400.access.AS400JDBCResultSet.next(AS400JDBCResultSet.java:1843)
```

I still don't get how the ODBC driver on the same machine dramatically outperforms the JDBC driver.  Too bad I can't leverage the ODBC driver in the target Linux environments where the JDBC driver is needed.

**Comment by jeber-ibm** [comment]
Looks like the ignore warnings isn't working as expected for the result set path.   I'll open a separate issue for that problem.  

Is there a way to adjust the query to avoid the time conversion warning from being generated on the server. 

If there is a lot of warnings, it probably is the main cause of your problem.

**Comment by jboarman** [comment]
Sure enough ... if I remove the 4 date fields (out of 75 total columns) from the SELECT, then query returns _much_ faster.  The response time went from 120 seconds down to 4 seconds, just be removing those 4 date columns from the query -- so this definitely supports your note @jeber-ibm that warnings are the issue.

However, I'm not sure I understand how to set the "ignore warnings" parameter.   I've tried setting it to every kind of value I can see in the warning detail, and nothing appears to stick.  I found this [sqlstate values table](https://www.ibm.com/docs/en/i/7.3?topic=codes-listing-sqlstate-values) in IBM docs that seems to indicate `22007` is the SQLSTATE for the SQLCODE of `SQL0181`.  That value does not appear to prevent the warnings, so I'm at a loss for whether the value is valid or the setting is just not working.

**Comment by jboarman** [comment]
**UPDATE:**  Good news _and_ Less Good News?

I confirmed the warnings are removed from the trace now using the new `ignore warnings=all` JDBC URL parameter (thanks @jeber-ibm).  HOWEVER, the performance problems remained.  🤯 

IBM Support compared traces from ODBC and JDBC connections and found that the ODBC driver had the `date format` setting defaulted to `iso` while the JDBC driver did not.  So, after explicitly setting that parameter, I found the query performance was now almost as fast as the ODBC driver when using the JDBC driver.

So ... does this mean there is a problem with the JT400's driver defaults?  Should we be matching IBM's ODBC driver default for this?  Or does that cause other problems?

I'm still doing testing as I worry that maybe other tables we're querying will have a different date format.  In that case, how would I handle a case of mixed date formats over the same connection?!  🤔

**Comment by jeber-ibm** [comment]
I'm surprised that the date format is still causing a performance problem.  It makes me wonder if there is still a Java exception that is being produced but being ignored by the driver. 

Unfortunately, the driver default date format has been set.  Because of compatibility issues, it is unlikely to be changed. 

The date format is connected with the JOB / connection used to access the data.  Internally, all dates are stored in a different format.  From the SQL reference, we can read the following. 

_A date is a three-part value (year, month, and day) designating a point in time under the Gregorian
calendar, which is assumed to have been in effect from the year 1 A.D.

The range of the year part is 0001 to 9999....

The internal representation of a date is a string of 4 bytes that contains an integer. The integer (called the
Scaliger number) represents the date._

You can see the range of the internal values using the following SQL statements. 

>values hex(date('0001-01-01'))
00001
001A4452
>values hex(date('9999-12-31'))
00001
0051FE2C

**Comment by sandman507th** [comment]
@jboarman, regarding an ODBC driver in your Linux environment, are you unable to use the Linux Application Package here : https://www.ibm.com/support/pages/ibm-i-access-client-solutions  ?

**Comment by jboarman** [comment]
@sandman507th, that's an interesting idea.  I'm not sure how to install that driver in Linux.  I was looking for a JAR file that installs as a standard Java dependency, but I have a coworker that has used linuxodbc in databricks ... so that very well might be an option to try next time if one can't resolve a similar issue.
