### ISSUE TITLE
Question about a JDBC Connection Pool overhead which hangs iBMI server

### ISSUE THREAD

**Issue by edubois1976** [IBM/JTOpen#116]
Hi everyone,

We use JTopen version 7.8 in production to run SQL queries on an iBMI server from a Tomcat server hosted on a LINUX virtual machine.

We encountered on 3 occasions a failure that we cannot explain.

Our JDBC connection pool is overloaded (120 connections) and threads seem to be waiting on com.ibm.as400.access.AS400ThreadedServer.receive(AS400ThreadedServer.java:339).

A SQL query was targeted in particular but after optimizing it (<50ms), the problem is still present.

We suspected a lock on the iBMI server on one of the files used by the targeted stored procedure.

A test with an exclusive lock shows that JTOpen returns an error to the Java code and that the pool behaves well.

**Restarting the Tomcat instance results in the deletion of QZDASOINIT jobs which saturate the iBMI server and the whole system restarts fine !**

We have read in the JTOpen documentation that it is possible to use parameters to manage a timeOut on the SQL query:

"jdbc:as400://xxx.xxx.xxx.xxx;thread used=false;socket timeout=6;login timeout=6"

Have you ever tried these settings? What about performance and robustness?

Is it possible to use timeouts on SQL queries? 
**Does the cancellation result in the cancellation of the QZDASOINIT jobs on the iBMI server as a result?**

It seems to be possible since version 7.8, do we have any feedback on this option?

Thanks for your help

E.Dubois

**Comment by jeber-ibm** [comment]
Do not use the socket timeout, as that will cause problems with the connection.   If the socket timeout occurs, then the connection will become unusable and a new connection will need to be established. 

The wait on AS400ThreadedServer.receive just means the thread is waiting for data to be received from the server.  
It looks like your application is overloading the server, which cannot quick send a response.  

It is possible to to use a query timeout.  To do that, you need to set the "query timeout mechanism=cancel" JDBC property and then the code must use Statement.setQueryTimeout to set the timeout seconds.   When the timeout expires, the JDBC driver will send an SQL CANCEL request to the server.   This should cause the QZDASOINIT job to end the current SQL operation and return.  The QZDASOINIT job should still be usable after this point. 

Note that the SQL CANCEL will only stop SQL work.  If you are calling a stored procedure that is doing non-SQL work, then the SQL CANCEL request may not work until the non-SQL work is complete.
