### ISSUE TITLE
Missing get/set network timeout for connections

### ISSUE THREAD

**Issue by fdlk** [IBM/JTOpen#117]
I use `net.sf.jt400:jt400@20.0.0` with the `java11` classifier.
When I start up, the hikari connection pool warns me
> Driver does not support get/set network timeout for connections. (The driver does not support this function. (thread used != false))

**Comment by jeber-ibm** [comment]
To use the network timeout for connections, you must also set "thread used=false" 

Here are the details as described in the JAVADOC for the JDBC Properties. 

Sets the millisecond timeout used by the network socket. This determines the maximum number of milliseconds a JDBC connection will block on a read operation while waiting for a server response.
NOTE1: If the timeout occurs, then the connection becomes unusable.
NOTE2: If this property is used, it must be set to be shorter than the time used by a database request. If not, a long running database operation will cause the timeout to occur.
NOTE3: The socket timeout should only be used if the "thread used" property is set to false. By default, the JDBC driver will create a thread that is always blocked on a socket read waiting for a server response, and a connection idle longer than the socket timeout will drop the connection.
