### ISSUE TITLE
Missing artefacts in Maven repository for classifier java8, java11 and native

### ISSUE THREAD

**Issue by MNeuling** [IBM/JTOpen#156]
It is not possible to use a Java 8 or Java 11 dependency for jt400 in a Maven POM .
The artifacts for the classifiers java8, java11 and native are missing.
https://mvnrepository.com/artifact/net.sf.jt400

Therefore a dependency declaration as follows doesn't work.

```xml
<dependency>
	<groupId>net.sf.jt400</groupId>
	<artifactId>jt400</artifactId>
	<version>20.0.6</version>
	<classifier>java8</classifier>
</dependency>
```

Please add the missing classifiers to the distribution configuration.

**Comment by NicolaIsotta** [comment]
The artifacts exists, just look here:
https://repo1.maven.org/maven2/net/sf/jt400/jt400/20.0.6/

**Comment by MNeuling** [comment]
Sorry, I was wrong.
