### ISSUE TITLE
Missing jar files in version 20

### ISSUE THREAD

**Issue by MikSwens** [IBM/JTOpen#163]
It is clear from the documentation that several obsolete jar files were removed in the port from version 11 to 20 but there are several other, still useful and used, jar files that seem to be AWOL:
composer.jar
jui400.jar
outputwriters.jar
reportwriter.jar
tes.jar  (graphical debugger...probably used most of all)
uitools.jar
util400.jar

These need to be added to the project.

**Comment by jeber-ibm** [comment]
The source for these jar files is not part of JTOpen, so JTOpen does not have a way to build them.  

If these jar files are needed, then will need to be obtained from an IBM i system from the /QIBM/ProdData/OS400/jt400/lib directory.
