### ISSUE TITLE
JDBC connection property addition to prevent password expiration warning dialogs

### ISSUE THREAD

**Issue by draebyllek** [IBM/JTOpen#209]
When using DBeaver and an iSeries, you are pestered for a period of time (seems like two weeks) about your password expiring sometime in the far-away future.  Who cares?  I only care about THE DAY OF when my password expires.  When you have several connections open to one or more iSeries, it becomes very annoying to have to answer two of these questions per session.  I am proposing a connection property that I can specify in an SQL client JDBC config to get rid of this annoyance.  The connection property would basically have the effect of the following Java code:

AS400.setPasswordExpirationWarningDays(-1);

Of course the property should be configurable and allowing for -1.

**Comment by jeber-ibm** [comment]
The "prompt=false" JDBC property will prevent the expiration warning from being displayed. 
I'm not sure there is much value in adding another JDBC property for this.
