### ISSUE TITLE
Request: Publish the Java 11 version of the driver to Maven Central

### ISSUE THREAD

**Issue by SergiyKolesnikov** [IBM/JTOpen#212]
The Java 11 version of the driver is available in the GitHub releases, but it is not available on Maven Central. Please publish the driver to Maven Central, so that it can be downloaded by build tools.

**Comment by jeber-ibm** [comment]
It's there.  You just have to use the classifer to get it.  For example, in Maven, 

`    <dependency>
      <groupId>net.sf.jt400</groupId>
      <artifactId>jt400</artifactId>
      <version>20.0.7</version>
      <classifier>java11</classifier>
      <scope>provided</scope>
    </dependency>
`
