### ISSUE TITLE
typesafety: `JobLog.getMessages()`

### ISSUE THREAD

**Issue by ThePrez** [IBM/JTOpen#39]
should return typed Enumeration

**Comment by ThePrez** [comment]
Probably best to wait for the `QueuedMessageEnumeration` changes that will be done as part of #40

**Comment by sandesh2526** [comment]
Hi! Once the #40 is resolved can I take this? I have read the description regarding type safety in issue #42. Will need a little help for testing it out though. Is there any documentation that I can refer to for building and setting up the environment? 
Thanks!

**Comment by ThePrez** [comment]
Just noting here that #40 looks to be resolved. @sandesh2526 no rush, feel free to work on whenever time permits for you. Thanks!
