### ISSUE TITLE
typesafety: `MessageQueue.getMessages()`

### ISSUE THREAD

**Issue by ThePrez** [IBM/JTOpen#40]
could return typed Enumeration

**Comment by sumitdethe27** [comment]
Hey @ThePrez, I want to work on this issue, Also it will help a lot if you can give more background information about it.

**Comment by ThePrez** [comment]
Hi, @sumitdethe27, thanks for volunteering!

The background is very similar as [this comment](https://github.com/IBM/JTOpen/issues/42#issuecomment-1540662434) in issue #42, except that I don't think we need to worry about `List` implementations for now.

I think you can start with adding typesafety to `QueuedMessageEnumeration` and follow the usage from there. 

Feel free to reach out with questions

**Comment by ThePrez** [comment]
As commented on issues #37 and #39, those issues also rely on the `QueuedMessageEnumeration` changes you will need to make here.

**Comment by sumitdethe27** [comment]
Thankyou @ThePrez I'm working on this issue.
