### ISSUE TITLE
typesafety: `Permission` class

### ISSUE THREAD

**Issue by ThePrez** [IBM/JTOpen#41]
`getAuthorizedUsers()` and `getUserPermissions()` could return typed Enumerations

**Comment by ThePrez** [comment]
Should also have `List` variants, for instance:
```java
public List<UserPermission> getUserPermissionsList()
```
and 
```java
public List<String> getAuthorizedUsersList()
```

**Comment by worksofliam** [comment]
Made #76 based on the feature suggestion. They should be done in two PRs
