### ISSUE TITLE
Jar files not autoloading JDBC driver

### ISSUE THREAD

**Issue by jeber-ibm** [IBM/JTOpen#52]
The jar files do not autoload the JDBC driver.  This was accomplished in the ant build using the following. 

		
		<copy  encoding="ISO-8859-1" tofile="${sourceroot}/build/META-INF/services/java.sql.Driver"
	          overwrite="yes"
	          preservelastmodified="yes"
	          file="${sourceroot}/build/java.sql.Driver" />

When the jar is packaged, it needs to have the META-INFO/services/java.sql.Driver file defined with the appropriate contents. 

The following test program can be used to test. 

import java.sql.*; 
public class TestAutoLoad {
    public static void main(String args[]) {
	try {
	    Connection c = DriverManager.getConnection("jdbc:as400:somehost"); 
	} catch (Exception e) {
	    e.printStackTrace();
	} 
    }
}

This fails with the following error when the JDBC driver is not autoloaded. 

> java -cp java6/jt400.jar:. TestAutoLoad
java.sql.SQLException: No suitable driver found for jdbc:as400:somehost
	at java.sql.DriverManager.getConnection(DriverManager.java:700)
	at java.sql.DriverManager.getConnection(DriverManager.java:281)
	at TestAutoLoad.main(TestAutoLoad.java:5)

If the JDBC driver is autoloaded, the following error is encountered. 

$ java -cp /qibm/proddata/os400/jt400/lib/java6/jt400.jar:.  TestAutoLoad
java.sql.SQLNonTransientConnectionException: The application requester cannot establish the connection. (somehost)
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:884)

The regression test that was supposed to detect this was broken.  I have fixed the testcase.  It is. 
java test.JDRunit 7586T JDJSTPjdbc 24

**Comment by ThePrez** [comment]
Great find. Thank you!
