### ISSUE TITLE
Feature suggestion: `.netrc` support

### ISSUE THREAD

**Issue by ThePrez** [IBM/JTOpen#53]
Ability to read/understand `.netrc` files in much the same way as common Linux command line utilities

**Comment by kadler** [comment]
I don't think we should encourage such poor security behavior.

**Comment by jeber-ibm** [comment]
I agree with Kevin.   Using a .netrc to store passwords is very insecure

**Comment by ThePrez** [comment]
Thanks for the input, folks. Closing
