### ISSUE TITLE
Need PCML version '8.0' specified in `pcml.dtd`

### ISSUE THREAD

**Issue by ThePrez** [IBM/JTOpen#60]
There was supposed to be a new version value of ‘8.0’ in pcml.dtd located in com/ibm/as400/data/pcml.dtd.

```bash
<!ATTLIST pcml
          version  (1.0 | 2.0 | 3.0 | 4.0 | 6.0 | 7.0) #REQUIRED
>
```
This was in support of the attribute that was added for the data tag.

```bash
boolean (true | false) #IMPLIED
```

Resulting behavior is a failure validating PCML, for instance:
> XML for object not valid. Attribute "version" with value "8.0" must have a value from the list "1.0 2.0 3.0 4.0 6.0 7.0 ".

**Comment by jeber-ibm** [comment]
I think that there is more that needs to be done than just sayving version 8.   I'm not sure that PCML support for boolean was added.   To test, you'll need to create an RPG programs with the boolean data type.  The compile should produce the PCML that can then be used for the Program Call.

**Comment by ThePrez** [comment]
> I think that there is more that needs to be done than just saying version 8. I'm not sure that PCML support for boolean was added. To test, you'll need to create an RPG programs with the boolean data type. The compile should produce the PCML that can then be used for the Program Call.

Thank you. I agree. I should have opened the PR as a draft. @nadiramra may be doing some of the smoke test as well
