### ISSUE TITLE
On Java8: Connection to PWDLVL 4 system fails with NoSuchMethodError

### ISSUE THREAD

**Issue by jeber-ibm** [IBM/JTOpen#69]
Recreate. 

java   -jar  java8/jt400.jar  jdbc:as400:$SYSTEM $USERID $PASSWORD
Exception in thread "main" java.lang.NoSuchMethodError: java/nio/CharBuffer.flip()Ljava/nio/CharBuffer; (loaded from /usr/java8_64/jre/lib/rt.jar by <Bootstrap Loader>) called from class com.ibm.as400.access.AS400ImplRemote (loaded from file:/afs/rchland.ibm.com/usr5/jt400/WWW/jtopen/java8/jt400.jar by sun.misc.Launcher$AppClassLoader@a299bf4).
	at com.ibm.as400.access.AS400ImplRemote.generateSaltForPasswordLevel4(AS400ImplRemote.java:4739)
	at com.ibm.as400.access.AS400ImplRemote.generatePwdTokenForPasswordLevel4(AS400ImplRemote.java:4757)
	at com.ibm.as400.access.AS400ImplRemote.getPassword(AS400ImplRemote.java:1890)
...

Looks like a common problem with code compiled with Java 9 then run on Java 8. 
See -- https://discuss.elastic.co/t/nosuchmethoderror-charbuffer-flip-using-java-8-with-spring-boot-and-apm-1-0-0/156870 -- which says.... 

That's a very strange one. In Java 9, CharBuffer overrides the Buffer#flip method which returns a CharBuffer. In Java 8, it doesn't override the method but the method still exists in the superclass Buffer but that one has a different return type than the class it was compiled against.

**Comment by jeber-ibm** [comment]
some suggestions from https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

**Comment by ThePrez** [comment]
I was afraid this might happen. I think we can leverage this: https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html

**Comment by ThePrez** [comment]
Change pushed in to PR #70. My smoke testing has positive results. 

```fortran
>"C:\Program Files\Eclipse Adoptium\jdk-8.0.352.8-hotspot"\bin\java -showversion  -jar jt400-20.0.0-alpha-2-java8.jar jdbc:as400:mysystem user password
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b08, mixed mode)

>select * from qiws.qcustcdt
CUSNUM,LSTNAM,INIT,STREET,CITY,STATE,ZIPCOD,CDTLMT,CHGCOD,BALDUE,CDTDUE
938472,Henning ,G K,4859 Elm Ave ,Dallas,TX,75217,5000,3,37.00,0.00
839283,Jones   ,B D,21B NW 135 St,Clay  ,NY,13041,400,1,100.00,0.00
392859,Vine    ,S S,PO Box 79    ,Broton,VT,5046,700,1,439.00,0.00
938485,Johnson ,J A,3 Alpine Way ,Helen ,GA,30545,9999,2,3987.50,33.50
397267,Tyron   ,W E,13 Myrtle Dr ,Hector,NY,14841,1000,1,0.00,0.00
389572,Stevens ,K L,208 Snow Pass,Denver,CO,80226,400,1,58.75,1.50
846283,Alison  ,J S,787 Lake Dr  ,Isle  ,MN,56342,5000,3,10.00,0.00
475938,Doe     ,J W,59 Archer Rd ,Sutter,CA,95685,700,2,250.00,100.00
693829,Thomas  ,A N,3 Dove Circle,Casper,WY,82609,9999,2,0.00,0.00
593029,Williams,E D,485 SE 2 Ave ,Dallas,TX,75218,200,1,25.00,0.00
192837,Lee     ,F L,5963 Oak St  ,Hector,NY,14841,700,2,489.50,0.50
583990,Abraham ,M T,392 Mill St  ,Isle  ,MN,56342,9999,3,500.00,0.00
>
```

**Comment by ThePrez** [comment]
Ope, my smoke test isn't against a pwdlevel 4 system! Will re-test this weekend

**Comment by ThePrez** [comment]
oof, none of my systems are PWDLVL 4. We'll touch base next week regarding test

**Comment by ThePrez** [comment]
Was able to smoke test against a proper PWDLVL 4 system and verified the fix
