### ISSUE TITLE
Purpose of raw classes in repo

### ISSUE THREAD

**Issue by worksofliam** [IBM/JTOpen#80]
What's the sitch with these dirs/objects existing in repo? Initial reaction is to not have .class files checked in.

* https://github.com/IBM/JTOpen/tree/main/include/com/sun/kjava
* https://github.com/IBM/JTOpen/tree/main/build (has .class files)

**Comment by ThePrez** [comment]
The ones in [main/include/com/sun/kjava](https://github.com/IBM/JTOpen/tree/main/include/com/sun/kjava) could be removed as it's related to old (now-removed) ME stuff. 

The ones in [main/build](https://github.com/IBM/JTOpen/tree/main/build), however, are actually used by the `maven-antrun` plugin directly (and they use `ant` libraries). I agree that we should stop shipping the .class files and instead build them in a Maven step. I haven't gotten around to it, and I'm glad we have this issue open so we don't lose sight of it. 

When we drop Java 7 support in version 21.x, we need to take some effort to clean up unused things in that directory anyway. That might be a good time to clean up the .class files and do the proper thing.
