### ISSUE TITLE
Support for CCSID 65535 for Data Translation - JT400 jar ver 10.7

### ISSUE THREAD

**Issue by shussain-tibco** [IBM/JTOpen#85]
Hi Team,

Case Background :
We are developing a product , it is called TIBCO ActiveMatrix BusinessWorks Plug-in for IBMi ,which runs on a base business platform product called TIBCO ActiveMatrix BusinessWorks ( BW) on Windows operating system. This BW plugin for IBMi is basically a Java GUI client to connect to AS400 system which can Call a AS400 Program ,Service program , Read and Write Data Queue . Listen on a Data Queue , Read Message Queue, List spool files , spool file to pdf conversion etc .

The product concerned here i.e. TIBCO BW IBMi plugin has JT400 jar 10.7 version embedded in it .While creating a connection between Tibco IBMi Plugin with a AS400 server , we provide following details like Username , Password , Server address , Max number of connections , Connection age and CCSID.
The field CCSID in the connection resource is the CCSID used to translate string fields in and out of the binary payloads exchanged between the plug-in and the server.

Problem Statement :
When we give CCSID 65535 in the plugin connection resource , we are able to connect with the AS400 server successfully. But when we run the Tibco BW IBMi plugins Read Data Queue Activity or Read Message Queue Activity or ListSpool File activity we get the below error :

**Error Statement: ** Error received while running Read Data Queue activity:

An error occured while communicating with the IBMi server when running the Read Data Queue Activity
<causedby> java.io.UnsupportedEncodingException: CCSID 65535
<causedby> java.lang.ClassNotFoundException: com.ibm.as400.access.ConvTable65535 cannot be found by com.tibco.bw.as400.as400jars_1.2.0.001</causedby></causedby>

Question:
Does the Jt400 jar 10.7 version or for that matter is there any JT400 jar version which support CCSID 65535 for data translation ?

** Full Detailed Erorr Message : **

023-05-29T17:18:06,488 ERROR [pool-78-thread-1] com.tibco.bw.palette.as400.runtime.ReadQueueActivity - TIBCO-BW-PALETTE-AS400-590004: Exception occurred while executing the activity [ReadQueue].
2023-05-29T17:18:06,490 ERROR [bwEngThread:In-Memory Process Worker-3] com.tibco.bw.core - TIBCO-BW-CORE-500050: The BW process [tibco.bw instance faulted, JobId [bw0a107], ProcessInstanceId [bw0a107], ParentProcessInstanceId [-], Module [tibco.bw, Application [tibco.bw.
<causedby> TIBCO-BW-CORE-500051: Activity [ReadQueue]</causedby> fault.
<causedby> com.tibco.bw.palette.as400.runtime.exception.IBMiRemoteException: An error occured while communicating with the IBMi server when running the activity: tibco.bw.ibmi.sample.KeyQueueOperation/ReadQueue.The detailed message is CCSID 65535.-</causedby>

{ActivityName=ReadQueue, ProcessName=[tibco.bw|http://tibco.bw/].ibmi.sample.KeyQueueOperation, ModuleName=[tibco.bw|http://tibco.bw/].ibmi.sample}
<causedby> java.io.UnsupportedEncodingException: CCSID 65535
<causedby> java.lang.ClassNotFoundException: com.ibm.as400.access.ConvTable65535 cannot be found by com.tibco.bw.as400.as400jars_1.2.0.001</causedby></causedby>

From the above error message it can be seen that the class ConvTable65535 is not present in JT400 jar 10.7 version.

Do we have a fix for this ? Is there any official date when we can expect this fix for CCSID 65535 ? 

Also, Please let us know if there is any other JT400 jar version which support CCSID 65535 for data translation ?

As per the IBMi Globalization document  , if CCSID is set as 65535 then this means that all character data tagging support
on the system is turned off. Is this true for only "character" datatypes or every datatype ?
(https://www.ibm.com/docs/en/ssw_ibm_i_74/nls/rbagsmstpdf.pdf)

**Comment by kadler** [comment]
> Does the Jt400 jar 10.7 version or for that matter is there any JT400 jar version which support CCSID 65535 for data translation?

No, this doesn't make any sense. CCSID 65535 means the data is binary and should not be converted. If you want to convert the data, you need to set a valid CCSID for conversion.

**Comment by shussain-tibco** [comment]
Thanks for the clarification.
